"""
Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATABASE_NAME = config('DATABASE_NAME')
DATABASE_PASSWORD = config('DATABASE_PASSWORD')
DATABASE_USER = config('DATABASE_USER')

ENVIRONMENT = config('ENVIRONMENT', default='development')

if ENVIRONMENT == 'production':
    WSGI_APPLICATION = "cumulus.wsgi.application"
    DEBUG = False
    ALLOWED_HOSTS = ['cumulus.pythonanywhere.com']
    # Production-only settings here, e.g.:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DATABASE_NAME,
            'USER': DATABASE_USER,
            'PASSWORD': DATABASE_PASSWORD,
            'HOST': 'cumulus.mysql.pythonanywhere-services.com',
            'PORT': '3306',  # Leave empty for the default MySQL port (3306)
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'",
            },
        }
    }
else:
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    # Local dev DB config
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

SECRET_KEY = config('DJANGO_KEY')

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "stores.apps.StoresConfig",
    "products.apps.ProductsConfig",
    "orders.apps.OrdersConfig",
    "rest_framework",
    "rest_framework.authtoken",
    'office.apps.OfficeConfig',
    'lots.apps.LotsConfig',
    # 'axes',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "cumulus.middleware.MaintenanceModeMiddleware",
    # 'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = "cumulus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'], 
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG 
SESSION_COOKIE_AGE = 86400

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'products', 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://code.jquery.com")
CSP_CONNECT_SRC = ("'self'", "http://localhost:8000")  # Add your domain or source here

# Authentication backends
AUTHENTICATION_BACKENDS = [
    # 'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Axes config
# AXES_FAILURE_LIMIT = 3
# AXES_COOLOFF_TIME = 0.5  # 30 minutes
# AXES_RESET_ON_SUCCESS = True
# AXES_LOCK_OUT_BY_USER = True
# AXES_LOCK_OUT_BY_IP = True
# AXES_LOCKOUT_TEMPLATE = 'axes/lockout.html' 

# FOR_YEAR might be for germ samples mostly??
FOR_YEAR = 26

# Change this to the next year once we shut the website down in mid-November
CURRENT_ORDER_YEAR = 26
PACKET_PRICE = 2.40
SITE_MAINTENANCE_MODE = True
TRANSITION = False  # whether we are in the transition period between years (July - Dec)

PKG_SIZES = ["Net wt. 1/8 oz", "Net wt. 1/4 oz", "Net wt. 1/2 oz", "Net wt. 1 oz", "Approx. 10 seeds", "Approx. 15 seeds", "Approx. 20 seeds", "Approx. 20-25 seeds", "Approx. 25 seeds", 
             "Approx. 25-30 seeds", "Approx. 30 seeds", "Approx. 30-35 seeds", "Approx. 35 seeds", "Approx. 40 seeds", "Approx. 50 seeds", 
             "Approx. 75 seeds", "Approx. 75-100 seeds", "Approx. 100 seeds", "Approx. 150 seeds", "Approx. 200 seeds", "Approx. 250 seeds", "Approx. 300 seeds", 
             "Approx. 500 seeds", "Approx. 1000 seeds", "Approx. 5k seeds", "Approx. 10k seeds", "Approx. 25k seeds", "Net wt. 1/4 g", "Net wt. 1/3 g", 
             "Net wt. 1/2 g", "Net wt. 1 g", "Net wt. 2 g"]

SKU_SUFFIXES = ["pkt", "1/8oz", "1/4oz", "1/2oz", "1oz", "2oz", "1/4lb", "1/2lb", "1lb", "2.5lb", "5lb", "1/4g",
                "1g", "50s", "100s", "200s", "250s", "500s", "1Ms", "5Ms", "10Ms", "25Ms"]

ENV_TYPES =["Cosmos", "Flower", "Herb", "Poppy", "Sunflower", "Sweet Pea", "Zinnia", "LG Coffee", "SM Coffee"]


CROPS = ['AMARANTH', "BACHELOR'S BUTTON", 'BASKET FLOWER', 'BORAGE', 'BUPLEURUM', 'CALENDULA', 'CELOSIA', 'CERINTHE', 'CHINA ASTER', 
         'CHINESE DELPHINIUM', 'CHINESE FORGET-ME-NOT', 'CLEOME', 'COLUMBINE', 'COREOPSIS', 'COSMOS', 'COSMOS SULPHUREUS', 'CRASPEDIA', 
         'DATURA WRIGHTII', 'DIANTHUS', 'DIDISCUS', 'EDIBLE FLOWER MIX', 'ERYNGIUM', 'FLAX', "FOUR O'CLOCKS", 'FOXGLOVE', 'GYPSOPHILA', 
         "JACOB'S LADDER", 'LARKSPUR', 'MARIGOLD', 'MIGNONETTE', 'MORNING GLORY', 'MULLEIN, TURKISH', 'MULLEIN, VERBASCUM', 'NASTURTIUM', 
         'NICOTIANA', 'NIGELLA BUCHARICA', 'NIGELLA HISPÁNICA', 'NIGELLA PAPILLOSA', 'ORNAMENTAL GRASS', 'PEARL YARROW', 'PHACELIA TANACETIFOLIA', 
         'POPPY', 'POPPY, BREADSEED', 'POPPY, CALIFORNIA', 'POPPY, ICELAND', 'POPPY, PEONY', 'POPPY, SHIRLEY', 'RUDBECKIA', 'RUDBECKIA TRILOBA', 
         'SAINFOIN', 'SALVIA', 'SAPONARIA', 'SCABIOSA', 'SIBERIAN YARROW', 'SNAPDRAGON', 'STRAWFLOWER', 'SUNFLOWER', 'SUNFLOWER, MEXICAN', 
         'SWEET PEA', 'ZINNIA', 'BASIL', 'BASIL, GREEK', 'BASIL, SACRED', 'CHERVIL', 'CILANTRO', 'CULINARY HERBS', 'DILL', 'ECHINACEA', 
         'GERMAN CHAMOMILE', 'HYSSOP', 'LICORICE MINT', 'MARIGOLD', 'MARSHMALLOW', 'MONARDA', 'MULLEIN', 'NEPITELLA', 'NIGELLA SATIVA', 
         'PARSLEY, FLATLEAF', 'TRIGONELLA']


# this is a general category. Example: "Cuke and Melon", "Bean and Pulse", "Greens", "Brassicas", "Flower", "Herb"
GROUPS = ["Flower", "Herb"]

# this is a more specific category. Example: "Cuke", "Melon", "Bean", "Pea", "Lettuce", "Tomato"
VEG_TYPES = ["CHRYSANTHEMUM", "AMARANTH", "ASTER", "BACHELOR'S BUTTON", "BASKET FLOWER",
             "BORAGE", "BUPLEURUM", "CALENDULA", "CELOSIA", "CERINTHE", "CHINESE FORGET-ME-NOT", "CLEOME", "COLUMBINE",
             "COREOPSIS", "COSMOS", "CRASPEDIA", "DATURA", "DELPHINIUM", "DIANTHUS", "DIDISCUS", "ERYNGIUM", "FLAX",
             "FOUR O'CLOCKS", "FOXGLOVE", "GRASS", "GYPSOPHILA", "JACOB'S LADDER", "LARKSPUR", "MARIGOLD", "MIGNONETTE",
             "MORNING GLORY", "MULLEIN", "NASTURTIUM", "NICOTIANA", "NIGELLA", "PHACELIA", "POPPY", "RUDBECKIA",
             "SAINFOIN", "SALVIA", "SAPONARIA", "SCABIOSA", "SNAPDRAGON", "STRAWFLOWER", "SUNFLOWER", "SWEET PEA",
             "YARROW", "ZINNIA", "BASIL", "CHAMOMILE", "CHERVIL", "CILANTRO", "DILL", "ECHINACEA", "HYSSOP",
             "LICORICE MINT", "MARSHMALLOW", "MONARDA", "PARSLEY"]

SUPERGROUPS = ["Flower",
               "Herb",
              ] 

SUBTYPES = ["AMARANTH", "BREADSEED", "CALIFORNIA", "CHINA", "CHINESE", "FLATLEAF", "ICELAND", "MEXICAN (TITHONIA)", 
            "ORNAMENTAL","PEARL", "PEONY", "PURPUREA", "SACRED BASIL", "SHIRLEY", "SIBERIAN","TRAILING"]

CATEGORIES = ["Flowers", "Herbs"]

