# Generated by Django 5.2.5 on 2026-02-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_labelprint_mix_lot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variety",
            name="veg_type",
        ),
    ]
