# Generated by Django 5.2.5 on 2026-02-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_variety_veg_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variety",
            name="supergroup",
        ),
    ]
