# Generated by Django 5.2.5 on 2026-02-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_variety_supergroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variety",
            name="group",
        ),
    ]
