# Generated by Django 5.2.5 on 2026-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_variety_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="var_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
